default_platform :ios

platform :ios do
  before_all do
  	ciutils
  	cocoapods
  	# en_setup_keychain
  end

  lane :test do
  	scan(code_coverage: true)
  	slather
  end

  lane :build do
  	gym
  end

  after_all do |lane|
    # en_remove_keychain
  end

  error do |lane, exception|
  	# en_remove_keychain
  end
end